"""Build the canonical Pegoles mark SVGs + the TS geometry module.

Usage: python3 scripts/brand/build.py   (after trace.py)
Reads:  assets/brand/geometry.json
Writes: assets/brand/pegoles-mark.svg          full-color mark + glow
        assets/brand/pegoles-mark-glyph.svg    flat single-color glyph
        packages/ui/src/brand/markGeometry.generated.ts

Coordinates: the mark is re-centred into a 640 x 640 artboard (1 unit =
1 source pixel, no scaling) so the fitted numbers stay comparable with the
PNG. brandlib.svg_origin() is the single definition of that offset.
"""

from __future__ import annotations

import json

import brandlib as bl

TS_OUT = bl.REPO / "packages/ui/src/brand/markGeometry.generated.ts"
FULL_SVG = bl.BRAND_DIR / "pegoles-mark.svg"
GLYPH_SVG = bl.BRAND_DIR / "pegoles-mark-glyph.svg"
MAX_STOPS = 7


def thin(stops: list[dict], limit: int = MAX_STOPS) -> list[dict]:
    if len(stops) <= limit:
        return stops
    idx = sorted({round(i * (len(stops) - 1) / (limit - 1)) for i in range(limit)})
    return [stops[i] for i in idx]


def paths(geo: dict) -> dict[str, str]:
    origin = bl.svg_origin(geo)
    return {
        "outer": bl.cubics_to_path(bl.outer_shape(geo["outer"]), origin),
        "inner": bl.cubics_to_path(bl.inner_shape(geo["inner"]), origin),
        "eyeLeft": bl.cubics_to_path(bl.eye_shape(geo["eyes"][0]), origin),
        "eyeRight": bl.cubics_to_path(bl.eye_shape(geo["eyes"][1]), origin),
    }


def full_intensity(hex_color: str) -> str:
    c = hex_color.lstrip("#")
    rgb = [int(c[i : i + 2], 16) for i in (0, 2, 4)]
    k = 255 / max(max(rgb), 1)
    return "#" + "".join(f"{min(255, round(v * k)):02X}" for v in rgb)


def stops_xml(stops: list[dict]) -> str:
    return "".join(f'<stop offset="{s["offset"]}" stop-color="{s["color"]}"/>' for s in stops)


def palette(geo: dict) -> dict:
    c = geo["colors"]
    return {
        "ringBody": thin(c["ring_body"]),
        "ringLight": thin(c["ring_depth_10"]),
        "ringRim": thin(c["ring_rim"]),
        "ringInnerEdge": thin(c["ring_inner_edge"]),
        "eye": c["eye_vertical_ramp"],
        "glowNear": c["glow_outside"][0]["color"],
        # Hue of the source's own halo, normalized to full intensity.
        "glow": full_intensity(c["glow_outside"][0]["color"]),
        "opening": c["opening"],
    }


DEFAULT_LOOK: dict[str, float] = {
    "glow_far_opacity": 0.55,
    "glow_far_std": 64,
    "glow_near_opacity": 0.5,
    "glow_near_std": 12,
    "glow_tight_opacity": 0.5,
    "glow_tight_std": 5,
    "light_width": 30,
    "light_std": 14,
    "light_opacity": 0.9,
    "rim_width": 5,
    "rim_std": 1.4,
    "rim_opacity": 1.0,
    "edge_width": 5,
    "edge_opacity": 1.0,
    "shade_opacity": 0.8,
    "shade_std": 18,
    "eye_glow_opacity": 0.55,
    "eye_glow_std": 9,
    "body_gain": 1.0,
}
LOOK_JSON = bl.BRAND_DIR / "look.json"


def load_look() -> dict[str, float]:
    look = dict(DEFAULT_LOOK)
    if LOOK_JSON.exists():
        look.update(json.loads(LOOK_JSON.read_text())["params"])
    return look


def gain(stops: list[dict], k: float) -> list[dict]:
    out = []
    for s in stops:
        c = s["color"].lstrip("#")
        rgb = [min(255, round(int(c[i : i + 2], 16) * k)) for i in (0, 2, 4)]
        out.append({"offset": s["offset"], "color": "#" + "".join(f"{v:02X}" for v in rgb)})
    return out


def full_svg(geo: dict, p: dict[str, str], pal: dict, look: dict[str, float] | None = None) -> str:
    """Static full-color mark. Filters here are fine: the file is static."""
    lk = look or load_look()
    f = {k: round(float(v), 3) for k, v in lk.items()}
    b = bl.mark_bounds(geo)
    y0, y1 = b["y"], b["y"] + b["height"]
    grad = f'gradientUnits="userSpaceOnUse" x1="0" y1="{y0:.2f}" x2="0" y2="{y1:.2f}"'
    eye_top = min(e["cy"] - e["h"] / 2 for e in geo["eyes"]) - bl.svg_origin(geo)[1]
    eye_bot = max(e["cy"] + e["h"] / 2 for e in geo["eyes"]) - bl.svg_origin(geo)[1]
    eye_grad = f'gradientUnits="userSpaceOnUse" x1="0" y1="{eye_top:.2f}" x2="0" y2="{eye_bot:.2f}"'
    ring = p["outer"] + p["inner"]
    eyes = p["eyeLeft"] + p["eyeRight"]
    body = gain(pal["ringBody"], f["body_gain"])
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="-120 -120 880 880" width="880" height="880" role="img" aria-labelledby="t">
<title id="t">Pegoles</title>
<!-- Generated by scripts/brand/build.py from assets/brand/geometry.json + look.json (vector
     trace of assets/brand/source/pegoles-mark-source.png). Do not edit by hand; do not redesign. -->
<defs>
<linearGradient id="body" {grad}>{stops_xml(body)}</linearGradient>
<linearGradient id="light" {grad}>{stops_xml(pal["ringLight"])}</linearGradient>
<linearGradient id="rim" {grad}>{stops_xml(pal["ringRim"])}</linearGradient>
<linearGradient id="edge" {grad}>{stops_xml(pal["ringInnerEdge"])}</linearGradient>
<linearGradient id="eye" {eye_grad}>{stops_xml(pal["eye"])}</linearGradient>
<clipPath id="ring-clip"><path clip-rule="evenodd" d="{ring}"/></clipPath>
<clipPath id="open-clip"><path d="{p["inner"]}"/></clipPath>
<filter id="glow-far" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="{f["glow_far_std"]}"/></filter>
<filter id="glow-near" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="{f["glow_near_std"]}"/></filter>
<filter id="glow-tight" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="{f["glow_tight_std"]}"/></filter>
<filter id="soft" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="{f["light_std"]}"/></filter>
<filter id="rim-blur" x="-10%" y="-10%" width="120%" height="120%"><feGaussianBlur stdDeviation="{f["rim_std"]}"/></filter>
<filter id="shade" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="{f["shade_std"]}"/></filter>
<filter id="eye-glow" x="-150%" y="-80%" width="400%" height="260%"><feGaussianBlur stdDeviation="{f["eye_glow_std"]}"/></filter>
</defs>
<g id="glow">
<path d="{ring}" fill-rule="evenodd" fill="{pal["glow"]}" opacity="{f["glow_far_opacity"]}" filter="url(#glow-far)"/>
<path d="{ring}" fill-rule="evenodd" fill="{pal["glow"]}" opacity="{f["glow_near_opacity"]}" filter="url(#glow-near)"/>
<path d="{ring}" fill-rule="evenodd" fill="{pal["glow"]}" opacity="{f["glow_tight_opacity"]}" filter="url(#glow-tight)"/>
</g>
<g id="inner-shadow" clip-path="url(#open-clip)">
<path d="{p["inner"]}" fill="#000617" opacity="{f["shade_opacity"]}" filter="url(#shade)" transform="translate(320 333) scale(0.9) translate(-320 -333)"/>
</g>
<g id="ring" clip-path="url(#ring-clip)">
<path d="{ring}" fill-rule="evenodd" fill="url(#body)"/>
<path d="{p["outer"]}" fill="none" stroke="url(#light)" stroke-width="{f["light_width"]}" opacity="{f["light_opacity"]}" filter="url(#soft)"/>
<path d="{p["outer"]}" fill="none" stroke="url(#rim)" stroke-width="{f["rim_width"]}" opacity="{f["rim_opacity"]}" filter="url(#rim-blur)"/>
<path d="{p["inner"]}" fill="none" stroke="url(#edge)" stroke-width="{f["edge_width"]}" opacity="{f["edge_opacity"]}" filter="url(#rim-blur)"/>
</g>
<path id="eye-glow" d="{eyes}" fill="#169CFD" opacity="{f["eye_glow_opacity"]}" filter="url(#eye-glow)"/>
<path id="eyes" d="{eyes}" fill="url(#eye)"/>
</svg>
"""


def glyph_svg(p: dict[str, str]) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640" width="640" height="640" role="img" aria-label="Pegoles">
<!-- Generated by scripts/brand/build.py. Flat glyph (currentColor) for monochrome/template/mask use. -->
<path id="ring" fill="currentColor" fill-rule="evenodd" d="{p["outer"]}{p["inner"]}"/>
<path id="eyes" fill="currentColor" d="{p["eyeLeft"]}{p["eyeRight"]}"/>
</svg>
"""


def ts_module(geo: dict, p: dict[str, str], pal: dict) -> str:
    origin = bl.svg_origin(geo)
    eyes = [
        {
            "cx": round(e["cx"] - origin[0], 2),
            "cy": round(e["cy"] - origin[1], 2),
            "width": round(e["w"], 2),
            "height": round(e["h"], 2),
        }
        for e in geo["eyes"]
    ]
    inner = geo["inner"]
    opening = {
        "x": round(inner["cx"] - inner["hw"] - origin[0], 2),
        "y": round(inner["y0"] - origin[1], 2),
        "width": round(2 * inner["hw"], 2),
        "height": round(inner["y1"] - inner["y0"], 2),
    }
    data = {
        "size": bl.ARTBOARD,
        "bounds": bl.mark_bounds(geo),
        "opening": opening,
        "paths": p,
        "eyes": eyes,
        "colors": pal,
        # Lighting recipe (blur radii / widths in artboard units) shared by
        # the static SVG and the runtime PegolesMark layers.
        "look": {k: round(float(v), 3) for k, v in load_look().items()},
    }
    body = json.dumps(data, indent=2)
    return (
        "// GENERATED by scripts/brand/build.py from assets/brand/geometry.json + look.json.\n"
        "// Vector trace of assets/brand/source/pegoles-mark-source.png — do not edit\n"
        "// by hand and do not redesign; re-run the brand pipeline instead.\n\n"
        f"export const MARK_GEOMETRY = {body} as const;\n\n"
        "export type MarkGeometry = typeof MARK_GEOMETRY;\n"
    )


def main() -> None:
    geo = json.loads(bl.GEOMETRY_JSON.read_text())
    p = paths(geo)
    pal = palette(geo)
    FULL_SVG.write_text(full_svg(geo, p, pal))
    GLYPH_SVG.write_text(glyph_svg(p))
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(ts_module(geo, p, pal))
    for f in (FULL_SVG, GLYPH_SVG, TS_OUT):
        print(f"wrote {f.relative_to(bl.REPO)} ({f.stat().st_size} B)")


if __name__ == "__main__":
    main()
