// Generated by scripts/egress/update-threat-feed.sh; do not edit.
// SHA-256 of each compiled-in snapshot file (data/*.txt.gz).
pub(super) const MALWARE_DOMAINS_SHA256: &str =
    "8ef35313e40f10b5de0e5112a75cc7a0e832d4576de3084d5c40a0b55a2bb8e2";
pub(super) const MALWARE_URLS_SHA256: &str =
    "e6b776c8f6d211db4c3dda60095997a951c187adccc4a83d2ecbe571ece96970";
pub(super) const PHISHING_DOMAINS_SHA256: &str =
    "3c97f7d2aa258186f89539f7193a2756e3083706aba5ad03de11fe149d5cf7e2";
pub(super) const ADULT_DOMAINS_SHA256: &str =
    "734892b9a97e49f970d06d1516b3ec6936bfb366dcc0fe0a76d280dcdee1d429";
pub(super) const GAMBLING_DOMAINS_SHA256: &str =
    "76d98bba5e8369f37acc4917e398e0db35041883cd6ba5f73c23d9599afd8f7a";
