// GENERATED by scripts/brand/build.py from assets/brand/geometry.json + look.json.
// Vector trace of assets/brand/source/pegoles-mark-source.png — do not edit
// by hand and do not redesign; re-run the brand pipeline instead.

export const MARK_GEOMETRY = {
  "size": 640,
  "bounds": {
    "x": 6.67,
    "y": 26.77,
    "width": 626.67,
    "height": 586.46
  },
  "opening": {
    "x": 65.09,
    "y": 125.2,
    "width": 511.23,
    "height": 415.8
  },
  "paths": {
    "outer": "M92.86 86.18C127.06 48.36 175.68 26.77 226.67 26.77L413.33 26.77C464.33 26.77 512.94 48.36 547.14 86.18L595.96 140.18C620.02 166.78 633.34 201.38 633.34 237.25L633.34 418.9C633.34 454.76 619.51 489.23 594.73 515.15L549.56 562.39C518.52 594.87 475.55 613.23 430.63 613.23L209.37 613.23C164.45 613.23 121.48 594.87 90.44 562.39L45.27 515.15C20.49 489.23 6.67 454.76 6.67 418.9L6.67 237.25C6.67 201.38 19.99 166.78 44.04 140.18L92.86 86.18Z",
    "inner": "M228.57 125.2L412.84 125.2C560.95 125.2 576.32 225.54 576.32 266.52L576.32 395.64C576.32 436.63 561.01 541 408.01 541L233.4 541C80.41 541 65.09 436.63 65.09 395.64L65.09 266.52C65.09 225.54 80.46 125.2 228.57 125.2Z",
    "eyeLeft": "M206.97 261.68C224.62 261.68 238.92 275.98 238.92 293.63L238.92 372.71C238.92 390.36 224.62 404.67 206.97 404.67C189.32 404.67 175.02 390.36 175.02 372.71L175.02 293.63C175.02 275.98 189.32 261.68 206.97 261.68Z",
    "eyeRight": "M435.3 261.62C452.96 261.62 467.28 275.94 467.28 293.6L467.28 372.69C467.28 390.35 452.96 404.66 435.3 404.66C417.64 404.66 403.32 390.35 403.32 372.69L403.32 293.6C403.32 275.94 417.64 261.62 435.3 261.62Z"
  },
  "eyes": [
    {
      "cx": 206.97,
      "cy": 333.17,
      "width": 63.91,
      "height": 142.99
    },
    {
      "cx": 435.3,
      "cy": 333.14,
      "width": 63.95,
      "height": 143.04
    }
  ],
  "colors": {
    "ringBody": [
      {
        "offset": 0.066,
        "color": "#1D87FD"
      },
      {
        "offset": 0.19,
        "color": "#2A97FD"
      },
      {
        "offset": 0.343,
        "color": "#157BFD"
      },
      {
        "offset": 0.497,
        "color": "#014CDE"
      },
      {
        "offset": 0.651,
        "color": "#003EC9"
      },
      {
        "offset": 0.805,
        "color": "#0038BD"
      },
      {
        "offset": 0.932,
        "color": "#00237C"
      }
    ],
    "ringLight": [
      {
        "offset": 0.026,
        "color": "#90E0FD"
      },
      {
        "offset": 0.19,
        "color": "#74CCFD"
      },
      {
        "offset": 0.343,
        "color": "#56BCFD"
      },
      {
        "offset": 0.497,
        "color": "#228EFD"
      },
      {
        "offset": 0.651,
        "color": "#2491FE"
      },
      {
        "offset": 0.805,
        "color": "#2695FD"
      },
      {
        "offset": 0.973,
        "color": "#0046D9"
      }
    ],
    "ringRim": [
      {
        "offset": 0.018,
        "color": "#E0F8FD"
      },
      {
        "offset": 0.19,
        "color": "#BFF0FC"
      },
      {
        "offset": 0.342,
        "color": "#BCECFC"
      },
      {
        "offset": 0.497,
        "color": "#92E4FC"
      },
      {
        "offset": 0.729,
        "color": "#A0E4FB"
      },
      {
        "offset": 0.881,
        "color": "#72D0FC"
      },
      {
        "offset": 0.998,
        "color": "#1773D9"
      }
    ],
    "ringInnerEdge": [
      {
        "offset": 0.178,
        "color": "#4DB1FD"
      },
      {
        "offset": 0.342,
        "color": "#4BB3FC"
      },
      {
        "offset": 0.42,
        "color": "#4098F0"
      },
      {
        "offset": 0.497,
        "color": "#2084F0"
      },
      {
        "offset": 0.652,
        "color": "#1275E5"
      },
      {
        "offset": 0.808,
        "color": "#0140C3"
      },
      {
        "offset": 0.871,
        "color": "#022D8C"
      }
    ],
    "eye": [
      {
        "offset": 0.0,
        "color": "#E2F2F8"
      },
      {
        "offset": 0.25,
        "color": "#A2DFFD"
      },
      {
        "offset": 0.5,
        "color": "#7DCFFD"
      },
      {
        "offset": 0.75,
        "color": "#5AC3FD"
      },
      {
        "offset": 1.0,
        "color": "#5CCAF6"
      }
    ],
    "glowNear": "#032883",
    "glow": "#064EFF",
    "opening": "#000617"
  },
  "look": {
    "glow_far_opacity": 0.978,
    "glow_far_std": 139.459,
    "glow_near_opacity": 0.696,
    "glow_near_std": 59.044,
    "glow_tight_opacity": 0.619,
    "glow_tight_std": 6.192,
    "light_width": 48.201,
    "light_std": 11.853,
    "light_opacity": 0.996,
    "rim_width": 9.537,
    "rim_std": 2.211,
    "rim_opacity": 0.987,
    "edge_width": 6.609,
    "edge_opacity": 0.968,
    "shade_opacity": 0.996,
    "shade_std": 47.988,
    "eye_glow_opacity": 0.725,
    "eye_glow_std": 15.761,
    "body_gain": 0.937
  }
} as const;

export type MarkGeometry = typeof MARK_GEOMETRY;
