// GENERATED by scripts/brand/build.py from assets/brand/geometry.json + look.json.
// Vector trace of assets/brand/source/pegoles-mark-source.png — do not edit
// by hand and do not redesign; re-run the brand pipeline instead.

export const MARK_GEOMETRY = {
  "size": 640,
  "bounds": {
    "x": 6.33,
    "y": 25.83,
    "width": 627.34,
    "height": 588.35
  },
  "opening": {
    "x": 65.12,
    "y": 125.11,
    "width": 512.0,
    "height": 416.58
  },
  "paths": {
    "outer": "M96.14 82.26C128.77 46.32 175.07 25.83 223.61 25.83L416.38 25.83C464.93 25.83 511.22 46.32 543.86 82.26L596.16 139.84C620.29 166.42 633.67 201.03 633.67 236.94L633.67 418.93C633.67 455.44 619.54 490.54 594.25 516.87L548.55 564.46C518.04 596.22 475.91 614.18 431.87 614.18L208.12 614.18C164.09 614.18 121.95 596.22 91.45 564.46L45.74 516.87C20.45 490.54 6.33 455.44 6.33 418.93L6.33 236.94C6.33 201.03 19.7 166.42 43.84 139.84L96.14 82.26Z",
    "inner": "M225.53 125.11L416.7 125.11C568.45 125.11 577.12 239.83 577.12 260.4L577.12 399.88C577.12 429.8 563.95 541.69 412.57 541.69L229.66 541.69C78.28 541.69 65.12 429.8 65.12 399.88L65.12 260.4C65.12 239.83 73.78 125.11 225.53 125.11Z",
    "eyeLeft": "M207.11 261.6C224.73 261.6 239.01 275.88 239.01 293.5L239.01 373.01C239.01 390.63 224.73 404.91 207.11 404.91C189.49 404.91 175.21 390.63 175.21 373.01L175.21 293.5C175.21 275.88 189.49 261.6 207.11 261.6Z",
    "eyeRight": "M435.53 261.63C453.23 261.63 467.58 275.97 467.58 293.67L467.58 372.89C467.58 390.59 453.23 404.94 435.53 404.94C417.83 404.94 403.49 390.59 403.49 372.89L403.49 293.67C403.49 275.97 417.83 261.63 435.53 261.63Z"
  },
  "eyes": [
    {
      "cx": 207.11,
      "cy": 333.26,
      "width": 63.8,
      "height": 143.31
    },
    {
      "cx": 435.53,
      "cy": 333.28,
      "width": 64.09,
      "height": 143.31
    }
  ],
  "colors": {
    "ringBody": [
      {
        "offset": 0.067,
        "color": "#7D7F80"
      },
      {
        "offset": 0.19,
        "color": "#A0A2A3"
      },
      {
        "offset": 0.343,
        "color": "#797B7C"
      },
      {
        "offset": 0.496,
        "color": "#373738"
      },
      {
        "offset": 0.649,
        "color": "#363638"
      },
      {
        "offset": 0.803,
        "color": "#414243"
      },
      {
        "offset": 0.931,
        "color": "#242526"
      }
    ],
    "ringLight": [
      {
        "offset": 0.026,
        "color": "#E7E9EB"
      },
      {
        "offset": 0.19,
        "color": "#DEE0E2"
      },
      {
        "offset": 0.343,
        "color": "#C7C9CA"
      },
      {
        "offset": 0.496,
        "color": "#959798"
      },
      {
        "offset": 0.649,
        "color": "#A4A6A7"
      },
      {
        "offset": 0.803,
        "color": "#B0B2B3"
      },
      {
        "offset": 0.972,
        "color": "#6D6F6F"
      }
    ],
    "ringRim": [
      {
        "offset": 0.018,
        "color": "#FAFAFA"
      },
      {
        "offset": 0.189,
        "color": "#F9F9F9"
      },
      {
        "offset": 0.342,
        "color": "#F8F7F8"
      },
      {
        "offset": 0.496,
        "color": "#E8E8E9"
      },
      {
        "offset": 0.728,
        "color": "#F6F6F7"
      },
      {
        "offset": 0.879,
        "color": "#E8E9EA"
      },
      {
        "offset": 0.997,
        "color": "#D5D5D5"
      }
    ],
    "ringInnerEdge": [
      {
        "offset": 0.178,
        "color": "#9D9F9F"
      },
      {
        "offset": 0.341,
        "color": "#A6A8AA"
      },
      {
        "offset": 0.419,
        "color": "#747676"
      },
      {
        "offset": 0.497,
        "color": "#555658"
      },
      {
        "offset": 0.65,
        "color": "#525253"
      },
      {
        "offset": 0.805,
        "color": "#4A4B4C"
      },
      {
        "offset": 0.872,
        "color": "#343437"
      }
    ],
    "eye": [
      {
        "offset": 0.0,
        "color": "#F7F7F7"
      },
      {
        "offset": 0.25,
        "color": "#E6E9EA"
      },
      {
        "offset": 0.5,
        "color": "#C0C2C4"
      },
      {
        "offset": 0.75,
        "color": "#9DA0A0"
      },
      {
        "offset": 1.0,
        "color": "#EEEFF0"
      }
    ],
    "glowNear": "#3E3F41",
    "glow": "#F3F7FF",
    "opening": "#080808",
    "eyeGlow": "#F3F9FF"
  },
  "look": {
    "glow_far_opacity": 0.28,
    "glow_far_std": 162.705,
    "glow_near_opacity": 0.427,
    "glow_near_std": 59.044,
    "glow_tight_opacity": 0.184,
    "glow_tight_std": 8.827,
    "light_width": 54.821,
    "light_std": 15.834,
    "light_opacity": 0.989,
    "rim_width": 11.582,
    "rim_std": 2.588,
    "rim_opacity": 0.871,
    "edge_width": 9.963,
    "edge_opacity": 0.99,
    "shade_opacity": 0.991,
    "shade_std": 30.46,
    "eye_glow_opacity": 0.39,
    "eye_glow_std": 13.136,
    "body_gain": 0.691
  }
} as const;

export type MarkGeometry = typeof MARK_GEOMETRY;
