#!/usr/bin/env python3
"""Turn `pip freeze` of a working runtime into a hash-pinned lock file.

usage: <venv>/bin/pip freeze | python3 lock_runtime.py > workers/mlx/requirements.lock

Every requirement is pinned to one version and to the SHA-256 digests of
that version's files as published on PyPI, so `pip install
--require-hashes` refuses anything else (a compromised mirror or a
re-uploaded wheel fails closed). BUILD TIME ONLY.
"""

import json
import sys
import urllib.request


def digests(name, version):
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=60) as r:
        meta = json.load(r)
    return sorted({f["digests"]["sha256"] for f in meta["urls"]})


def main():
    out = ["# Generated by scripts/local-model/lock_runtime.py — do not edit by hand."]
    for line in sys.stdin:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "==" not in line:
            sys.exit(f"unpinned requirement: {line}")
        name, version = line.split("==", 1)
        hashes = digests(name, version)
        if not hashes:
            sys.exit(f"no files on PyPI for {line}")
        out.append(f"{name}=={version} \\")
        out.extend(f"    --hash=sha256:{h} \\" for h in hashes[:-1])
        out.append(f"    --hash=sha256:{hashes[-1]}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
